### ISSUE TITLE
How did you get the shadow on the screenshot?

### ISSUE THREAD

**Issue by sdushantha** [icyphox/crap#4]
I really like the MacOS like drop down shadow that you have on the screenshot of your file manager. How did you do that? I checked your dotfiles but couldnt find anything  which added the shadow to your screenshot.

**Comment by icyphox** [comment]
Ah, that's elementary's screenshot utility.

**Comment by sdushantha** [comment]
Oh, that makes sense. To bad that I cant really recreate that on i3wm :(

**Comment by icyphox** [comment]
It is possible to some extent. Play around with `imagemagick` to see if you can replicate it. [Here](https://www.imagemagick.org/discourse-server/viewtopic.php?t=16882)’s a discussion on this. 

That said, I was never able to fully replicate it. Couldn't achieve the transparency in the drop shadow.
